### ISSUE TITLE
MVDS Spec Alpha

### ISSUE THREAD

**Issue by oskarth** [status-im/bigbrother-specs#13]
Corresponding issue to current PR https://github.com/status-im/bigbrother-specs/pull/11

**Comment by oskarth** [comment]
Example sequence diagram:

![image](https://user-images.githubusercontent.com/1552237/59652132-029aef00-91bf-11e9-941e-a956be927097.png)

Zooming in:

![image](https://user-images.githubusercontent.com/1552237/59652144-0af32a00-91bf-11e9-9991-d7db9837dd00.png)

Referenced flow:

![image](https://user-images.githubusercontent.com/1552237/59652151-121a3800-91bf-11e9-8592-d4016927637b.png)


From *Communication Protocol Engineering* book

**Comment by StatusWrike** [comment]
➤ Jacek Sieka commented:

As far as 1.0 goes, this seems premature. I'd aim for, and call this an alpha version of the protocol, but in order to finalize it, it should go through a more rigorious implementation and real-world testing phase.

**Comment by StatusWrike** [comment]
➤ Oskar Thoren commented:

Agree. I think the intention with this was to refer to it being a "draft" v1 and minimal viable DS as opposed to DS. Simpler might be to just call it alpha. WDYT Dean Eigenmann?
